config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#index'

  resources :notifications
  post '/subscribers/unsubscribe', to: 'subscribers#destroy_by_subscription'
  resources :subscribers
  get '/events/upcoming', to: 'events#upcoming'
  resources :events
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save

        @subscribers = Subscriber.all
        @subscribers.each do |s|
          begin
            Webpush.payload_send(
              message: JSON.generate({
                title: @notification.title,
                body: @notification.body
              }),
              endpoint: s.endpoint,
              p256dh: s.p256dh,
              auth: s.auth,
              vapid: {
                subject: "verynice.party",
                public_key: ENV['VAPID_PUBLIC'],
                private_key: ENV['VAPID_PRIV']
              }
            )
          rescue Webpush::ExpiredSubscription => e
            # Delete subscriptions that are not valid anymore
            s.destroy
          end

          p "Sent push notification to ", s.endpoint
        end

        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:title, :body)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>
<%= link_to 'Home', root_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>
<%= link_to 'Home', root_path %>
<br>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.title %></td>
        <td><%= notification.body %></td>
        <td><%= notification.created_at %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>
<%= link_to 'Home', root_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notification.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @notification.body %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>
<%= link_to 'Home', root_path %>