config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#index'

  resources :notifications
  post '/subscribers/unsubscribe', to: 'subscribers#destroy_by_subscription'
  resources :subscribers
  get '/events/upcoming', to: 'events#upcoming'
  resources :events
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, :only => [:create, :destroy_by_subscription]

  # I'm pretty sure this is okay, because there are no 'logged in' users
  skip_before_action :verify_authenticity_token

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /subscribers/unsubscribe[.json]
  def destroy_by_subscription
    @subscriber = Subscriber.find_by(endpoint: params[:endpoint])
    if @subscriber
      @subscriber.destroy
      respond_to do |format|
        format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to subscribers_url, notice: 'Subscriber was not found.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:endpoint, :p256dh, :auth, :user_agent, :ip_addr, :name, :friend)
    end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_with(model: subscriber, local: true) do |form| %>
  <% if subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_agent %>
    <%= form.text_field :user_agent %>
  </div>

  <div class="field">
    <%= form.label :ip_addr %>
    <%= form.text_field :ip_addr %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :friend %>
    <%= form.check_box :friend %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>
<%= link_to 'Home', root_path %>

app/views/subscribers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscribers</h1>

<%= link_to 'Home', root_path %>
<br>
<table>
  <thead>
    <tr>
      <th>Endpoint</th>
      <th>User agent</th>
      <th>Ip addr</th>
      <th>Name</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.endpoint %></td>
        <td><%= subscriber.user_agent %></td>
        <td><%= subscriber.ip_addr %></td>
        <td><%= subscriber.name %></td>
        <td><%= subscriber.friend %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Back', subscribers_path %>

<%= link_to 'Home', root_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Endpoint:</strong>
  <%= @subscriber.endpoint %>
  <br>
  P256dh: <%= @subscriber.p256dh %>
  <br>
  Auth: <%= @subscriber.auth %>
</p>

<p>
  <strong>User agent:</strong>
  <%= @subscriber.user_agent %>
</p>

<p>
  <strong>Ip addr:</strong>
  <%= @subscriber.ip_addr %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subscriber.name %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @subscriber.friend %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>
<%= link_to 'Home', root_path %>